require 'boxy-cap/setup'
require 'boxy-cap/check'
require 'boxy-cap/nginx'
require 'boxy-cap/monit'
require 'boxy-cap/database'
require 'boxy-cap/delayed_job'
require 'boxy-cap/log'
require 'boxy-cap/rails'
require 'boxy-cap/unicorn'
require 'boxy-cap/git'
require 'boxy-cap/rake'
require 'boxy-cap/files'
require 'boxy-cap/rbenv_vars'
require 'boxy-cap/util'

